version: "3.8"

services:
  ecommerce-front:
    build: ./ecommerce-app
    container_name: ecommerce-front
    ports:
      - "3000:3000"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - product_service
      - rabbitmq

  product_service:
    build: ./microservices/product_service
    container_name: product_service
    env_file:
      - ./microservices/product_service/.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  inventory_service:
    build: ./microservices/inventory_service
    container_name: inventory_service
    env_file:
      - ./microservices/inventory_service/.env
    depends_on:
      - rabbitmq

  order_service:
    build: ./microservices/order_service
    container_name: order_service
    env_file:
      - ./microservices/order_service/.env
    depends_on:
      - rabbitmq

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./analytics/promtail/promtail-config.yaml:/etc/promtail/promtail.yml:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./analytics/grafana/provisioning:/etc/grafana/provisioning/dashboards
      - ./analytics/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki

    prometheus:
      image: prom/prometheus:v2.37.0
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      depends_on:
        - api-gateway

volumes:
  grafana-storage:
