version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - product_service
      - rabbitmq

  product_service:
    build: ./microservices/product_service
    container_name: product_service
    env_file:
      - ./microservices/product_service/.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  ecommerce-client:
    build: ./ecommerce-app
    container_name: ecommerce-client
    ports:
      - "3000:3000"
    env_file:
      - ./ecommerce-app/.env.local
    depends_on:
      - api-gateway

  inventory_service:
    build: ./microservices/inventory_service
    env_file:
      - ./microservices/inventory_service/.env
    depends_on:
      - rabbitmq

