# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"&\n\x10InventoryRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"5\n\x11InventoryResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\r\n\x05stock\x18\x02 \x01(\x05\x32_\n\x10InventoryService\x12K\n\x0e\x43heckInventory\x12\x1b.inventory.InventoryRequest\x1a\x1c.inventory.InventoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYREQUEST']._serialized_start=30
  _globals['_INVENTORYREQUEST']._serialized_end=68
  _globals['_INVENTORYRESPONSE']._serialized_start=70
  _globals['_INVENTORYRESPONSE']._serialized_end=123
  _globals['_INVENTORYSERVICE']._serialized_start=125
  _globals['_INVENTORYSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
