# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x14\n\x12GetProductsRequest\"A\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\x0c\n\x04slug\x18\x04 \x01(\t\"}\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12#\n\x08\x63\x61tegory\x18\x05 \x01(\x0b\x32\x11.product.Category\x12\x0e\n\x06images\x18\x06 \x03(\t\"9\n\x13GetProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product2Z\n\x0eProductService\x12H\n\x0bGetProducts\x12\x1b.product.GetProductsRequest\x1a\x1c.product.GetProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETPRODUCTSREQUEST']._serialized_start=26
  _globals['_GETPRODUCTSREQUEST']._serialized_end=46
  _globals['_CATEGORY']._serialized_start=48
  _globals['_CATEGORY']._serialized_end=113
  _globals['_PRODUCT']._serialized_start=115
  _globals['_PRODUCT']._serialized_end=240
  _globals['_GETPRODUCTSRESPONSE']._serialized_start=242
  _globals['_GETPRODUCTSRESPONSE']._serialized_end=299
  _globals['_PRODUCTSERVICE']._serialized_start=301
  _globals['_PRODUCTSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
