syntax = "proto3";
package product;

service ProductService {
  rpc GetProducts (GetProductsRequest) returns (GetProductsResponse);
}

// Mensaje de solicitud para obtener productos (aquí se pueden incluir filtros en el futuro)
message GetProductsRequest {}

// Mensaje para definir una categoría (si en algún momento necesitas información adicional)
message Category {
  int32 id = 1;
  string name = 2;
  string image = 3;
  string slug = 4;
}

// Mensaje para definir un producto, con todos los campos (incluso si el cliente REST no usa todos)
message Product {
  int32 id = 1;
  string title = 2;
  float price = 3;
  string description = 4;
  Category category = 5;
  repeated string images = 6;
}

// Mensaje de respuesta que contiene una lista de productos
message GetProductsResponse {
  repeated Product products = 1;
}
