# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb import inventory_pb2 as inventory__pb2


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckInventory = channel.unary_unary(
                '/inventory.InventoryService/CheckInventory',
                request_serializer=inventory__pb2.InventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )
        self.ReduceStock = channel.unary_unary(
                '/inventory.InventoryService/ReduceStock',
                request_serializer=inventory__pb2.InventoryUpdateRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryUpdateResponse.FromString,
                )


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckInventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReduceStock(self, request, context):
        """<-- nuevo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInventory,
                    request_deserializer=inventory__pb2.InventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
            'ReduceStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceStock,
                    request_deserializer=inventory__pb2.InventoryUpdateRequest.FromString,
                    response_serializer=inventory__pb2.InventoryUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/CheckInventory',
            inventory__pb2.InventoryRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReduceStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/ReduceStock',
            inventory__pb2.InventoryUpdateRequest.SerializeToString,
            inventory__pb2.InventoryUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
